import assert from 'node:assert/strict';
import { applyFilmTypeOverride, sanitizeFilmTypeOverride } from './filmTypeOverride.js';
import { buildRollProject, serializeRollProject, parseRollProject } from './rollProject.js';
const original = { filmType: 'color', filmTypeSource: 'auto', filmTypeConfidence: 'high', rollFrame: { locked: true }, cropRegion: { left: 10, width: 90 }, coreExposure: 25, repairStrokes: [{ x: 5 }], wbAutoConfidence: .8, wbR: 1.2, wbG: 1, wbB: .8 };
const next = applyFilmTypeOverride(original, { filmType: 'bw' });
assert.equal(next.filmType, 'bw');
assert.equal(next.filmTypeSource, 'manual');
assert.equal(next.rollFrame, null);
assert.equal(next.wbR, 1);
assert.deepEqual(next.cropRegion, original.cropRegion);
assert.deepEqual(next.repairStrokes, original.repairStrokes);
assert.equal(next.coreExposure, 25);
assert.equal(original.rollFrame.locked, true);
assert.equal(applyFilmTypeOverride({ ...original, wbUserOverride: true }, { filmType: 'bw' }).wbR, 1.2);
assert.equal(sanitizeFilmTypeOverride({ filmType: 'invalid' }), null);
assert.deepEqual(sanitizeFilmTypeOverride({ filmType: 'positive', positiveMode: 'edit', cropRegion: {} }), { filmType: 'positive', positiveMode: 'edit' });
const project = buildRollProject({ files: [{ name: 'unopened.dng', size: 123, filmTypeOverride: { filmType: 'bw', positiveMode: 'correct' } }] });
assert.deepEqual(parseRollProject(serializeRollProject(project)).files[0].filmTypeOverride, project.files[0].filmTypeOverride);
console.log('filmTypeOverride: isolated film selection, manual WB and unopened project persistence passed');
