import assert from 'node:assert/strict';
import { computeGainMap, packGainMapJpeg } from './gainMapJpeg.js';
import { listJpegSegments } from './exportMetadata.js';
import { parseTiff } from '../workers/tiffWriter.js';
const bytes = new Uint8Array([255,216,255,218,0,2,34,55,66,255,217]);
const packed = new Uint8Array(await (await packGainMapJpeg(new Blob([bytes]), new Blob([bytes]), { gainMax: 2 })).arrayBuffer());
const segments = listJpegSegments(packed), mpf = segments.find(s => s.marker === 226);
assert.equal(new TextDecoder().decode(mpf.data.subarray(0,4)), 'MPF\0');
const tags = parseTiff(mpf.data.subarray(4)).ifd0;
assert.equal(tags[0xb001].values[0], 2);
const entry = new Uint8Array(tags[0xb002].values), view = new DataView(entry.buffer);
const size = view.getUint32(4,true), offset = view.getUint32(24,true);
assert.equal(offset + 10, size);
assert.deepEqual(packed.subarray(size - (bytes.length - 2), size), bytes.subarray(2), 'primary compressed bytes unchanged');
assert.deepEqual([...packed.subarray(size,size+2)], [255,216]);
assert.match(new TextDecoder().decode(packed), /hdrgm:GainMapMax="2"/);
const sdr = { width: 4, height: 4, data: new Uint8ClampedArray(64).fill(128) };
const map = computeGainMap(sdr, { width: 4, height: 4, data: new Uint16Array(64).fill(128*257) });
assert.equal(map.data[0], 0, '16-bit precision alone must not fabricate HDR');
assert.equal(computeGainMap(sdr, null), null);
console.log('gain map: MPF offsets, secondary JPEG, metadata and unchanged SDR scan passed');
