import assert from 'node:assert/strict';
import {createRollSampleCache} from './rollSampleCache.js';
const cache=createRollSampleCache(48);
const a={data:new Uint8ClampedArray(8),__image16:{data:new Uint16Array([1,500,60000,65535])}};
const b={data:new Uint8ClampedArray(32)};
cache.put('a',a);cache.put('b',b);assert.equal(cache.bytes,48);
assert.equal(cache.take('a'),a);assert.equal(cache.bytes,32);assert.equal(a.__image16.data[2],60000);
cache.put('a',a);cache.put('c',{data:new Uint8ClampedArray(24)});
assert.equal(cache.take('b'),null);assert.equal(cache.bytes,40);
cache.put('large',{data:new Uint8ClampedArray(100)});assert.equal(cache.bytes,40);
cache.retainKeys(['c']);assert.equal(cache.bytes,24);assert.equal(cache.take('a'),null);
assert.equal(cache.buffers().size,1);
const tiled=createRollSampleCache(100);
tiled.put('t',{data:new Uint8ClampedArray(8),__analysisReference:{data:new Uint16Array(4)},__tileWorking:{data:new Uint8ClampedArray(4),__image16:{data:new Uint16Array(4)}}});
assert.equal(tiled.bytes,8+8+4+8,'a roll sample counts its tile context');assert.equal(tiled.buffers().size,4);
cache.clear();assert.equal(cache.bytes,0);assert.equal(cache.take('a'),null);
console.log('roll sample cache: exact 16-bit samples, consumption, eviction and byte cap passed');
