// Which files each scenario group runs on.
//
// synthetic (default, runs anywhere): generated by fixtures.mjs.
// real: NC_PERF_RAW_DIR (+ optional NC_PERF_RAW_FILES, a JSON list of names
// or paths like PHOTO_SESSION_RAW_FILES) and NC_PERF_ROLL_DIR. Real files are
// opened read-only, never copied; results store basenames only.

import { createHash } from 'node:crypto';
import { createReadStream, existsSync, readdirSync, statSync } from 'node:fs';
import { basename, isAbsolute, join, resolve } from 'node:path';

export const RAW_PATTERN = /\.(dng|nef|cr2|cr3|arw|rw2|raf|orf|iiq|tiff?|jpe?g|png)$/i;
export const HANG_RAW = '_DSC3111.NEF';

export function sha256File(path) {
  return new Promise((resolvePromise, reject) => {
    const hash = createHash('sha256');
    createReadStream(path, { flags: 'r' }).on('data', chunk => hash.update(chunk)).on('end', () => resolvePromise(hash.digest('hex'))).on('error', reject);
  });
}

function listDir(dir) {
  if (!dir || !existsSync(dir)) return [];
  return readdirSync(dir).filter(name => RAW_PATTERN.test(name) && !name.startsWith('.')).sort().map(name => join(dir, name));
}

export function realFileList(env = process.env) {
  const dir = env.NC_PERF_RAW_DIR ? resolve(env.NC_PERF_RAW_DIR) : null;
  if (env.NC_PERF_RAW_FILES) {
    const list = JSON.parse(env.NC_PERF_RAW_FILES);
    return list.map(entry => (isAbsolute(entry) ? entry : join(dir || '.', entry))).filter(existsSync);
  }
  return listDir(dir);
}

/**
 * Resolve the fixture groups: { singles, interactive, roll, export, hang, smoke }.
 * `synthetic` maps generated fixture names to { path, width, height, sha256 }.
 */
export function resolveFixtureGroups({ set, synthetic = {}, rollSize = 12, quick = false, only = null, env = process.env, repoRoot }) {
  const describe = (path, extra = {}) => ({ name: basename(path), path, ...extra });
  const fromSynthetic = name => synthetic[name] ? describe(synthetic[name].path, { width: synthetic[name].width, height: synthetic[name].height, sha256: synthetic[name].sha256, synthetic: true }) : null;
  const smoke = [describe(join(repoRoot, 'negative2positive', 'test-fixtures', 'negative-sample.jpg'), { width: null })];
  let singles, interactive, roll, exportRoll, hang;
  if (set === 'real') {
    const files = realFileList(env).map(path => describe(path));
    if (!files.length) throw new Error('--fixtures real needs NC_PERF_RAW_DIR (and optionally NC_PERF_RAW_FILES)');
    const rollDir = env.NC_PERF_ROLL_DIR ? resolve(env.NC_PERF_ROLL_DIR) : null;
    roll = listDir(rollDir).slice(0, rollSize).map(path => describe(path));
    singles = files;
    interactive = files;
    exportRoll = roll.length >= 3 ? [files[0], ...roll.filter(entry => entry.name !== files[0].name).slice(0, 3)] : [];
  } else {
    singles = ['synthetic-60mp-cfa.dng', 'synthetic-24mp-cfa.dng', 'synthetic-60mp-color.tif', 'synthetic-60mp-bw.tif', 'synthetic-24mp-color.tif'].map(fromSynthetic).filter(Boolean);
    interactive = ['synthetic-60mp-cfa.dng', 'synthetic-24mp-cfa.dng'].map(fromSynthetic).filter(Boolean);
    roll = Array.from({ length: rollSize }, (_, i) => fromSynthetic(`synthetic-roll-${String(i + 1).padStart(2, '0')}.dng`)).filter(Boolean);
    exportRoll = [fromSynthetic('synthetic-60mp-cfa.dng'), ...roll.slice(0, 3)].filter(Boolean);
  }
  const rawDir = env.NC_PERF_RAW_DIR ? resolve(env.NC_PERF_RAW_DIR) : null;
  const hangRaw = rawDir && existsSync(join(rawDir, HANG_RAW)) ? describe(join(rawDir, HANG_RAW)) : null;
  hang = hangRaw ? [hangRaw] : [fromSynthetic('synthetic-24mp-cfa.dng')].filter(Boolean).map(entry => ({ ...entry, label: `${entry.name} (synthetic stand-in for ${HANG_RAW})` }));
  if (only) {
    const keep = list => list.filter(entry => entry.name === only);
    singles = keep(singles);
    interactive = keep(interactive);
  }
  if (quick) {
    singles = singles.slice(0, 1);
    interactive = interactive.slice(0, 1);
  }
  return { singles, interactive, roll, export: exportRoll, hang, smoke };
}

/** Synthetic fixture names a scenario list needs. */
export function syntheticNamesFor(groups, { rollSize = 12, quick = false } = {}) {
  const names = new Set();
  const singles = ['synthetic-60mp-cfa.dng', 'synthetic-24mp-cfa.dng', 'synthetic-60mp-color.tif', 'synthetic-60mp-bw.tif', 'synthetic-24mp-color.tif'];
  const interactive = ['synthetic-60mp-cfa.dng', 'synthetic-24mp-cfa.dng'];
  const roll = Array.from({ length: rollSize }, (_, i) => `synthetic-roll-${String(i + 1).padStart(2, '0')}.dng`);
  for (const group of groups) {
    if (group === 'singles') (quick ? singles.slice(0, 1) : singles).forEach(name => names.add(name));
    if (group === 'interactive') (quick ? interactive.slice(0, 1) : interactive).forEach(name => names.add(name));
    if (group === 'roll') roll.forEach(name => names.add(name));
    if (group === 'export') { names.add('synthetic-60mp-cfa.dng'); roll.slice(0, 3).forEach(name => names.add(name)); }
    if (group === 'hang') names.add('synthetic-24mp-cfa.dng');
  }
  return [...names];
}

export function fileSize(path) {
  try { return statSync(path).size; } catch { return null; }
}
