"""Regenerate bundled Fusion Pixel coverage; requires fonttools[woff]==4.60.1."""
import json
from pathlib import Path
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
fonts = root / 'negative2positive/public/fonts/fusion-pixel'
coverage = None
for locale in ('zh_hans', 'zh_hant', 'ja', 'ko'):
    font = TTFont(fonts / f'fusion-pixel-12px-proportional-{locale}.otf.woff2')
    codes = sorted(font.getBestCmap())
    assert font['head'].unitsPerEm == 1200
    assert coverage is None or coverage == codes, 'Locale coverage differs'
    coverage = codes

ranges = []
for code in coverage:
    if ranges and code == ranges[-1][1] + 1:
        ranges[-1][1] = code
    else:
        ranges.append([code, code])
target = root / 'negative2positive/src/app/nativePixelFontCoverage.js'
target.write_text(
    '// Generated by scripts/inspect-native-pixel-font.py from bundled Fusion Pixel 2026.09.01.\n'
    '// Shared by SC, TC, JP and KR; distinguishes native glyphs from explicit missing-glyph fallback.\n'
    'export const nativePixelFontCoverage = ' + json.dumps(ranges, separators=(',', ':')) + ';\n'
)
print(f'{len(coverage)} characters, {len(ranges)} ranges -> {target.name}')
