/**
 * FilmPresets.js - Film preset definitions
 * 37 presets: 16 color negative, 18 B&W, 3 positive (slide)
 */

export const filmPresets = {
  // ============================
  // Color Negative Presets (16)
  // ============================
  'frontier-lab': {
    name: 'Frontier Lab',
    category: 'color',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'frontier',
      shadows: -24,
      highlights: -6,
      blacks: 0,
      whites: 2,
      saturation: 125,
      glow: 12,
      fade: 11,
      shadowRange: 8,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: -1,
      shadowTemp: 6,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 3,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'noritsu-lab': {
    name: 'Noritsu Lab',
    category: 'color',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'noritsu',
      shadows: -20,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 120,
      glow: 10,
      fade: 8,
      shadowRange: 7,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 4,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 2,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'portra-classic': {
    name: 'Portra Classic',
    category: 'color',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'natural',
      shadows: -15,
      highlights: -10,
      blacks: 0,
      whites: 0,
      saturation: 115,
      glow: 8,
      fade: 6,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: 1,
      shadowTint: -1,
      shadowTemp: 3,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 2,
      midCyan: 0,
      midTint: -1,
      midTemp: 1,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'gold-warm': {
    name: 'Gold Warm',
    category: 'color',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'natural',
      shadows: -18,
      highlights: -4,
      blacks: 0,
      whites: 2,
      saturation: 135,
      glow: 14,
      fade: 8,
      shadowRange: 7,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: -2,
      shadowTemp: 8,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 5,
      midCyan: 0,
      midTint: -1,
      midTemp: 3,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'superia-vivid': {
    name: 'Superia Vivid',
    category: 'color',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'natural',
      shadows: -22,
      highlights: -6,
      blacks: 0,
      whites: 2,
      saturation: 140,
      glow: 12,
      fade: 6,
      shadowRange: 7,
      highlightRange: 5,
      shadowCyan: 1,
      shadowTint: 0,
      shadowTemp: 4,
      highlightCyan: 0,
      highlightTint: 1,
      highlightTemp: 2,
      midCyan: 1,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'crystal-archive': {
    name: 'Crystal Archive',
    category: 'color',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'crystal',
      shadows: -20,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 125,
      glow: 10,
      fade: 8,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 3,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 2,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'cinema-stock': {
    name: 'Cinema Stock',
    category: 'color',
    settings: {
      toneProfile: 'filmic',
      enhancedProfile: 'natural',
      shadows: -10,
      highlights: -25,
      blacks: -10,
      whites: 0,
      saturation: 115,
      glow: 6,
      fade: 15,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 2,
      shadowTint: -1,
      shadowTemp: 5,
      highlightCyan: -1,
      highlightTint: 0,
      highlightTemp: 3,
      midCyan: 1,
      midTint: 0,
      midTemp: 2,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'standard-auto': {
    name: 'Standard Auto',
    category: 'color',
    settings: {
      toneProfile: 'standard',
      enhancedProfile: 'frontier',
      shadows: 0,
      highlights: 0,
      blacks: 2,
      whites: -2,
      saturation: 120,
      glow: 0,
      fade: 0,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'rich-depth': {
    name: 'Rich Depth',
    category: 'color',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'natural',
      shadows: -28,
      highlights: -10,
      blacks: -5,
      whites: 0,
      saturation: 130,
      glow: 8,
      fade: 4,
      shadowRange: 8,
      highlightRange: 6,
      shadowCyan: 0,
      shadowTint: -1,
      shadowTemp: 5,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 2,
      midCyan: 0,
      midTint: 0,
      midTemp: 1,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'neutral-clean': {
    name: 'Neutral Clean',
    category: 'color',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'natural',
      shadows: -10,
      highlights: -5,
      blacks: 0,
      whites: 0,
      saturation: 110,
      glow: 4,
      fade: 4,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'clean-contrast': {
    name: 'Clean Contrast',
    category: 'color',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'natural',
      shadows: -20,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 120,
      glow: 10,
      fade: 6,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 3,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 2,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'bold-contrast': {
    name: 'Bold Contrast',
    category: 'color',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'natural',
      shadows: -30,
      highlights: -12,
      blacks: -5,
      whites: 3,
      saturation: 130,
      glow: 14,
      fade: 6,
      shadowRange: 7,
      highlightRange: 6,
      shadowCyan: 0,
      shadowTint: -1,
      shadowTemp: 5,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 3,
      midCyan: 0,
      midTint: 0,
      midTemp: 1,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'portrait-warm': {
    name: 'Portrait Warm',
    category: 'color',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'frontier',
      shadows: -16,
      highlights: -6,
      blacks: 0,
      whites: 0,
      saturation: 118,
      glow: 10,
      fade: 8,
      shadowRange: 7,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: -1,
      shadowTemp: 6,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 4,
      midCyan: 0,
      midTint: -1,
      midTemp: 2,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'fashion-tone': {
    name: 'Fashion Tone',
    category: 'color',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'natural',
      shadows: -18,
      highlights: -10,
      blacks: 0,
      whites: 0,
      saturation: 115,
      glow: 6,
      fade: 10,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 1,
      shadowTint: -2,
      shadowTemp: 4,
      highlightCyan: -1,
      highlightTint: 1,
      highlightTemp: 2,
      midCyan: 0,
      midTint: -1,
      midTemp: 1,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'scanner-rich': {
    name: 'Scanner Rich',
    category: 'color',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'pakon',
      shadows: -22,
      highlights: -8,
      blacks: -3,
      whites: 0,
      saturation: 128,
      glow: 10,
      fade: 6,
      shadowRange: 7,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 4,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 2,
      midCyan: 0,
      midTint: 0,
      midTemp: 1,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'standard-flat': {
    name: 'Standard Flat',
    category: 'color',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'frontier',
      shadows: -12,
      highlights: -4,
      blacks: 0,
      whites: 0,
      saturation: 115,
      glow: 6,
      fade: 10,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 2,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 1,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'subtractDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },

  // ============================
  // B&W Presets (18)
  // ============================
  'selenium-cold': {
    name: 'Selenium Cold',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -15,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 4,
      fade: 6,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 2,
      shadowTint: 0,
      shadowTemp: -3,
      highlightCyan: 1,
      highlightTint: 0,
      highlightTemp: -2,
      midCyan: 1,
      midTint: 0,
      midTemp: -1,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'selenium-warm': {
    name: 'Selenium Warm',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -15,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 4,
      fade: 6,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: -1,
      shadowTint: -1,
      shadowTemp: 3,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 2,
      midCyan: 0,
      midTint: 0,
      midTemp: 1,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'warmtone': {
    name: 'Warmtone',
    category: 'bw',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'none',
      shadows: -18,
      highlights: -6,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 6,
      fade: 8,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: -2,
      shadowTint: -2,
      shadowTemp: 8,
      highlightCyan: -1,
      highlightTint: -1,
      highlightTemp: 5,
      midCyan: -1,
      midTint: -1,
      midTemp: 3,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'cooltone': {
    name: 'Cooltone',
    category: 'bw',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'none',
      shadows: -18,
      highlights: -6,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 6,
      fade: 8,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: 2,
      shadowTint: 1,
      shadowTemp: -6,
      highlightCyan: 1,
      highlightTint: 0,
      highlightTemp: -4,
      midCyan: 1,
      midTint: 0,
      midTemp: -2,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'palladium': {
    name: 'Palladium',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -12,
      highlights: -10,
      blacks: 5,
      whites: -3,
      saturation: 100,
      glow: 8,
      fade: 12,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: -1,
      shadowTint: -1,
      shadowTemp: 4,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 2,
      midCyan: 0,
      midTint: 0,
      midTemp: 1,
      layerOrder: 'colorFirst',
      wbTonality: 'subtractDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'fomatone': {
    name: 'Fomatone',
    category: 'bw',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'none',
      shadows: -20,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 6,
      fade: 6,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: -1,
      shadowTint: -2,
      shadowTemp: 6,
      highlightCyan: 0,
      highlightTint: -1,
      highlightTemp: 4,
      midCyan: 0,
      midTint: -1,
      midTemp: 2,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'kodak-brown': {
    name: 'Kodak Brown',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -16,
      highlights: -6,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 8,
      fade: 8,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: -3,
      shadowTint: -2,
      shadowTemp: 10,
      highlightCyan: -1,
      highlightTint: -1,
      highlightTemp: 6,
      midCyan: -1,
      midTint: -1,
      midTemp: 4,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'sepia-classic': {
    name: 'Sepia Classic',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -14,
      highlights: -6,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 6,
      fade: 10,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: -4,
      shadowTint: -3,
      shadowTemp: 12,
      highlightCyan: -2,
      highlightTint: -1,
      highlightTemp: 8,
      midCyan: -2,
      midTint: -1,
      midTemp: 5,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'sepia-deep': {
    name: 'Sepia Deep',
    category: 'bw',
    settings: {
      toneProfile: 'base_deep',
      enhancedProfile: 'none',
      shadows: -20,
      highlights: -10,
      blacks: -5,
      whites: 0,
      saturation: 100,
      glow: 4,
      fade: 6,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: -5,
      shadowTint: -3,
      shadowTemp: 14,
      highlightCyan: -2,
      highlightTint: -1,
      highlightTemp: 8,
      midCyan: -2,
      midTint: -2,
      midTemp: 6,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'cyanotype': {
    name: 'Cyanotype',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -14,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 6,
      fade: 8,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 6,
      shadowTint: 1,
      shadowTemp: -10,
      highlightCyan: 3,
      highlightTint: 0,
      highlightTemp: -6,
      midCyan: 2,
      midTint: 0,
      midTemp: -4,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'platinum': {
    name: 'Platinum',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -10,
      highlights: -10,
      blacks: 5,
      whites: -5,
      saturation: 100,
      glow: 10,
      fade: 14,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'subtractDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'cold-neutral': {
    name: 'Cold Neutral',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -15,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 4,
      fade: 4,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 1,
      shadowTint: 0,
      shadowTemp: -2,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: -1,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'warm-neutral': {
    name: 'Warm Neutral',
    category: 'bw',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -15,
      highlights: -8,
      blacks: 0,
      whites: 0,
      saturation: 100,
      glow: 4,
      fade: 4,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: -1,
      shadowTint: 0,
      shadowTemp: 2,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 1,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'high-contrast-bw': {
    name: 'High Contrast',
    category: 'bw',
    settings: {
      toneProfile: 'base_deep',
      enhancedProfile: 'none',
      shadows: -30,
      highlights: -15,
      blacks: -10,
      whites: 5,
      saturation: 100,
      glow: 0,
      fade: 0,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'soft-bw': {
    name: 'Soft B&W',
    category: 'bw',
    settings: {
      toneProfile: 'base_flat',
      enhancedProfile: 'none',
      shadows: -8,
      highlights: -4,
      blacks: 5,
      whites: -5,
      saturation: 100,
      glow: 10,
      fade: 14,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'subtractDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'filmic-bw': {
    name: 'Filmic B&W',
    category: 'bw',
    settings: {
      toneProfile: 'filmic',
      enhancedProfile: 'none',
      shadows: -10,
      highlights: -25,
      blacks: -10,
      whites: 0,
      saturation: 100,
      glow: 4,
      fade: 8,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'rich-bw': {
    name: 'Rich B&W',
    category: 'bw',
    settings: {
      toneProfile: 'filmic_rich',
      enhancedProfile: 'none',
      shadows: -10,
      highlights: -25,
      blacks: -20,
      whites: 0,
      saturation: 100,
      glow: 2,
      fade: 4,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'flat-bw': {
    name: 'Flat B&W',
    category: 'bw',
    settings: {
      toneProfile: 'filmic_flat',
      enhancedProfile: 'none',
      shadows: -10,
      highlights: -25,
      blacks: -10,
      whites: 0,
      saturation: 100,
      glow: 8,
      fade: 12,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'subtractDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },

  // ============================
  // Positive (Slide) Presets (3)
  // ============================
  'slide-neutral': {
    name: 'Slide Neutral',
    category: 'positive',
    settings: {
      toneProfile: 'base',
      enhancedProfile: 'none',
      shadows: -10,
      highlights: -5,
      blacks: 0,
      whites: 0,
      saturation: 110,
      glow: 4,
      fade: 4,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'neutralDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'slide-rich': {
    name: 'Slide Rich',
    category: 'positive',
    settings: {
      toneProfile: 'base_gamma',
      enhancedProfile: 'none',
      shadows: -20,
      highlights: -10,
      blacks: -5,
      whites: 0,
      saturation: 130,
      glow: 6,
      fade: 2,
      shadowRange: 6,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 2,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 1,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'addDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
  'slide-soft': {
    name: 'Slide Soft',
    category: 'positive',
    settings: {
      toneProfile: 'base_flat',
      enhancedProfile: 'none',
      shadows: -6,
      highlights: -4,
      blacks: 5,
      whites: -5,
      saturation: 108,
      glow: 8,
      fade: 10,
      shadowRange: 5,
      highlightRange: 5,
      shadowCyan: 0,
      shadowTint: 0,
      shadowTemp: 0,
      highlightCyan: 0,
      highlightTint: 0,
      highlightTemp: 0,
      midCyan: 0,
      midTint: 0,
      midTemp: 0,
      layerOrder: 'colorFirst',
      wbTonality: 'subtractDensity',
      curveResolutionType: 'auto_curve_pts',
    },
  },
};

export const presetCategories = {
  color: [
    'frontier-lab', 'noritsu-lab', 'portra-classic', 'gold-warm',
    'superia-vivid', 'crystal-archive', 'cinema-stock', 'standard-auto',
    'rich-depth', 'neutral-clean', 'clean-contrast', 'bold-contrast',
    'portrait-warm', 'fashion-tone', 'scanner-rich', 'standard-flat',
  ],
  bw: [
    'selenium-cold', 'selenium-warm', 'warmtone', 'cooltone',
    'palladium', 'fomatone', 'kodak-brown', 'sepia-classic',
    'sepia-deep', 'cyanotype', 'platinum', 'cold-neutral',
    'warm-neutral', 'high-contrast-bw', 'soft-bw', 'filmic-bw',
    'rich-bw', 'flat-bw',
  ],
  positive: [
    'slide-neutral', 'slide-rich', 'slide-soft',
  ],
};
